version: '3.8'
services:
  mongo:
    volumes:
      - ./data/mongo:/data/db
      - ./scripts:/data/db/scripts
    image: mongo:5.0.5
    container_name: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_DB: ${MONGO_DB}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
    - 27017:27017